pipeline {
    agent any

    environment {
        DOCKER_COMPOSE_FILE = "/var/jenkins_home/docker-compose.yml"
    }

    stages {
        // Build stage
        stage('Build Service') {
            steps {
                echo 'Building Service'
                dir('mountain') {
                    sh 'docker build -t mountain-service .'
                }
            }
        }

        // Test stage
        stage('Test') {
            steps {
                echo 'Testing Service'
                // 여기에 테스트 관련 작업을 추가할 수 있습니다.
            }
        }

        // Deploy stage
        stage('Deploy Service') {
            steps {
                echo 'Deploying Service'
                // 이미지 빌드 후, 컨테이너 중지 및 제거
                sh 'docker-compose -f ${DOCKER_COMPOSE_FILE} stop mountain || true'
                sh 'docker-compose -f ${DOCKER_COMPOSE_FILE} rm -f mountain || true'
                // 새로운 컨테이너 실행
                sh 'docker-compose -f ${DOCKER_COMPOSE_FILE} up -d --force-recreate --no-deps mountain'
            }
        }
    }
}
